### ISSUE TITLE
Feature Point Labeling Tool

### ISSUE THREAD

**Issue by DoongLi** [ericzzj1989/Awesome-Image-Matching#1]
Nice Repo! Hi Zhenjun, I have a question about image pairs feature point labeling tool，do you used or saw related tool about it ?

**Comment by ericzzj1989** [comment]
Hi, thanks for your interest.
Sorry, I have not used such kind of tool.
Are you also doing some reseach regarding local feature?

**Comment by DoongLi** [comment]
Thx for your reply! Actually, I want to test some image matching methods in our datasets, so I consider if I can label some image pairs for test.

**Comment by DoongLi** [comment]
By the way, Can I added you wechat?
